name: Deploy to DigitalOcean working

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          cd client
          npm install
          npm run build

      - name: Archive build artifacts
        run: tar -czf client/build.tar.gz -C client/build .
        shell: bash
        id: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: client/build.tar.gz
          target: /var/www/crm-app/build.tar.gz

