name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          cd client
          npm install
          npm run build
          if [ ! -d "build" ]; then
            echo "Build directory is empty or does not exist."
            exit 1
          fi
          tar -czf build.tar.gz -C build .

      - name: Deploy to DigitalOcean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: build.tar.gz
          target: /var/www/crm-app/build.tar.gz
