jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Increase the timeout limit
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /var/www/crm-app
            git pull origin main
            bash deploy.sh
