# name: Deploy to DigitalOcean workig

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
      
#       - name: Deploy to DigitalOcean Droplet
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.DROPLET_IP }}
#           username: ${{ secrets.DROPLET_USER }}
#           key: ${{ secrets.DROPLET_SSH_KEY }}
#           script: |
#             cd /var/www/crm-app
#             git pull origin main
#             bash deploy.sh


name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            # Increase timeout for the commands
            npm config set timeout 600000  # Set timeout to 10 minutes (600 seconds)

            # Navigate to the project directory
            cd /var/www/crm-app
            
            # Pull the latest code
            git pull origin main
            
            # Navigate to the client directory and install dependencies
            cd client
            
            # Skip deprecation warnings and install dependencies
            npm install --loglevel=error --no-optional
            
            # Build the client application
            npm run build
            
            # Optionally, if you have a server to restart, add this command
            # sudo systemctl restart your-server-service # Replace with your service name

            # If using a custom deploy script
            bash deploy.sh
