name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest updated on too
    steps:
      # Step 1: Checkout the latest code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Setup Node.js (use the appropriate Node.js version)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Set to the required Node.js version

      # Step 3: Deploy to DigitalOcean Droplet using SSH
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            # Navigate to the application directory
            cd /var/www/crm-app

            # Pull the latest changes from the main branch
            git pull origin main

            # Install dependencies for the backend
            npm install

            # Navigate to the frontend and install dependencies
            cd client
            npm install
            npm run build
            cd ..

            # Restart the application using PM2
            pm2 restart crm-app || pm2 start server.js --name crm-app

      # Step 4: Clear previous PM2 logs (optional, for maintenance)
      - name: Clear PM2 Logs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            pm2 flush
