name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 45  # Increased timeout

    steps:
      - uses: actions/checkout@v3  # Updated to v3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v3  # Updated to v3
        with:
          path: client/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('client/**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          cd client
          npm ci --prefer-offline --no-audit
        env:
          CI: true

      - name: Build frontend
        run: |
          cd client
          npm run build
        env:
          CI: true

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /var/www/crm-app
            git pull origin main
            bash deploy.sh